"""report_writer — the Reporting agent's write path for formal documents.

Like create_task, the agent only *proposes*: deterministic code validates the
structure and size, composes the markdown, and performs the insert.
"""
from __future__ import annotations

import datetime as dt
from typing import TYPE_CHECKING

from sqlalchemy.engine import Engine

from app.api.reports import save_report
from app.tools.base import Tool, ToolError

if TYPE_CHECKING:  # pragma: no cover
    from app.agents.base import ToolContext

MAX_SECTIONS = 20
MAX_HEADING = 100
MAX_SECTION_CONTENT = 8000
MAX_TOTAL = 40_000

REPORT_WRITER_SCHEMA = {
    "type": "object",
    "properties": {
        "title": {"type": "string", "description": "Report title (max 200 chars)."},
        "sections": {
            "type": "array",
            "description": "Ordered report sections.",
            "items": {
                "type": "object",
                "properties": {
                    "heading": {"type": "string", "description": "Section heading."},
                    "content": {
                        "type": "string",
                        "description": "Section body (markdown allowed: lists, tables, bold).",
                    },
                },
                "required": ["heading", "content"],
            },
        },
    },
    "required": ["title", "sections"],
}


def compose_markdown(title: str, sections: list[dict], *, agent: str) -> str:
    today = dt.date.today().isoformat()
    parts = [f"# {title}", f"*Generated by the {agent} agent on {today}.*"]
    for section in sections:
        parts.append(f"## {section['heading']}")
        parts.append(section["content"].strip())
    return "\n\n".join(parts) + "\n"


def validate_report_input(tool_input: dict) -> tuple[str, list[dict]]:
    title = (tool_input.get("title") or "").strip()
    if not title:
        raise ToolError("title is required.")
    if len(title) > 200:
        raise ToolError("title must be at most 200 characters.")

    sections = tool_input.get("sections")
    if not isinstance(sections, list) or not sections:
        raise ToolError("sections must be a non-empty array of {heading, content}.")
    if len(sections) > MAX_SECTIONS:
        raise ToolError(f"at most {MAX_SECTIONS} sections allowed.")

    cleaned = []
    total = 0
    for i, raw in enumerate(sections):
        if not isinstance(raw, dict):
            raise ToolError(f"section {i + 1} must be an object with heading and content.")
        heading = (raw.get("heading") or "").strip()
        content = (raw.get("content") or "").strip()
        if not heading or not content:
            raise ToolError(f"section {i + 1}: heading and content are both required.")
        if len(heading) > MAX_HEADING:
            raise ToolError(f"section {i + 1}: heading exceeds {MAX_HEADING} characters.")
        if len(content) > MAX_SECTION_CONTENT:
            raise ToolError(f"section {i + 1}: content exceeds {MAX_SECTION_CONTENT} characters.")
        total += len(heading) + len(content)
        cleaned.append({"heading": heading, "content": content})
    if total > MAX_TOTAL:
        raise ToolError(f"report exceeds {MAX_TOTAL} characters in total.")
    return title, cleaned


def make_report_writer_tool(engine: Engine) -> Tool:
    async def handler(tool_input: dict, ctx: "ToolContext") -> str:
        title, sections = validate_report_input(tool_input)
        content = compose_markdown(title, sections, agent=ctx.agent)
        report_id = save_report(
            engine, title=title, content=content, agent=ctx.agent, kind="report"
        )
        return (
            f"Saved report #{report_id}: {title!r} ({len(sections)} sections). "
            "It is now available on the Reports page."
        )

    return Tool(
        name="report_writer",
        description=(
            "Save a formal markdown report to the reports library (validated and "
            "persisted by deterministic code). Provide a title and ordered sections; "
            "section content may use markdown lists/tables. Gather and verify all "
            "numbers with sql_query BEFORE writing the report."
        ),
        input_schema=REPORT_WRITER_SCHEMA,
        handler=handler,
    )
